### ISSUE TITLE
SVG and SHP export possibly broken

### ISSUE THREAD

**Issue by ajrteale** [christiankaiser/ScapeToad#6]
Hello,

I've been a satisfied user of ScapeToad for many years, but for some reason the SVG and SHP export on my system has broken today.

When loaded from the command line, an attempt to export an SVG or SHP gives me the following error (after the output file has been selected):

Exception in thread "ShowDialog" java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
	at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
	at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
	at java.desktop/sun.awt.X11.GtkFileDialogPeer.lambda$setVisible$0(GtkFileDialogPeer.java:118)
	at java.base/java.lang.Thread.run(Thread.java:834)

The program hangs at this point and has to be terminated using Ctrl-C.

Could you please help?

**Comment by ajrteale** [comment]
Seems to have fixed itself now.  It was probably my machine.
